### ISSUE TITLE
Support for passing in Bundle args

### ISSUE THREAD

**Issue by SUPERCILEX** [hypertrack/smart-scheduler-android#2]

**Comment by jagan999** [comment]
I've added this enhancement as in the attached files and tested it locally. The way I created this capability is to add a method called setArgs(Bundle) to Job.Builder. You invoke this method to add arguments to the job just like you invoke setRequiredNetworkType, setRequiresCharging etc. I'm not familiar with how to integrate this code change into github and create a new version of the library. Can you please integrate the attached files and create a new version for others to use?

If you need to use the passed in Bundle in the onJobScheduled method of your SmartScheduler.JobScheduledCallback class, you just use job.getArgs() to get the passed in Bundle and voila, you're all set!
[Job.zip](https://github.com/hypertrack/smart-scheduler-android/files/923691/Job.zip)
